# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "235a1ada56f259be5c3168eb7bd3ebd6"
name = "Campaign manager"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true